s:
	gcc server.c -o server -Wall
	./server
	rm ./server

c:
	gcc client.c -o client -Wall
	./client
	rm ./client

check:
	gcc server.c -o server
	rm ./server
	gcc client.c -o client
	rm ./clientserver
